language: csharp
dist: xenial
sudo: false
dotnet: 2.2.101

matrix:
  fast_finish: true
  
  include:
    - os: linux
      mono: 5.14.0
    - os: osx
      osx_image: xcode9.3
      mono: 5.14.0

env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

script:
- dotnet build
